apiVersion: v1
kind: Pod
metadata:
  name: puchurl
  labels:
    app: puchurl
spec:
  containers:
    - name: puchurl
      image: puchurl:0.1
      imagePullPolicy: IfNotPresent   # use the image we loaded, don't try Docker Hub
      ports:
        - containerPort: 8080
      env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development